version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./mysite/Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/code
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"